const ESPECIALIDADES_BADGE_MAP: Record<string, string> = {
  'Acólito': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/acolito.png',
  'Aeroespacial': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/Aeroespacial.jpg',
  'Agricultor': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/agricultor.png',
  'Agricultor Urbano': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/agricultor_urbano.png',
  'Alfaiate': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/alfaiate-modista.jpg',
  'Ambientalista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/Ambientalista.png',
  'Animador da Fé': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/animador_fe.png',
  'Animador Liturgico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/animador_liturgico.png',
  'Artes Marciais': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/defesa-pessoal.png',
  'Astrónomo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/astronomo.png',
  'Atleta': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/atleta.png',
  'Ator': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/ator.jpg',
  'Bibliotecário': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/bibliotecario.png',
  'Biblista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/biblista.png',
  'Biólogo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/biologo.png',
  'Bom Consumidor': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/bom_consumidor.png',
  'Botânico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/botanico.png',
  'Bushcraft': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/bushcraft.png',
  'Campista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/campista.png',
  'Canoista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/canoista.png',
  'Cantor': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/cantor.jpg',
  'Cantor Liturgico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/cantor-liturgico.jpg',
  'Carpinteiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/carpinteiro.png',
  'Carpinteiro Naval': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/carpinteiro_naval.png',
  'Cavaleiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/cavaleiro.png',
  'Ciclista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/ciclista.png',
  'Cidadão Cristão': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/cidadao_cristao.png',
  'Cidadão do Mundo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/cidadao_mundo.png',
  'Cidadão Europeu': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/cidadao_europeu.png',
  'Cidadão Lusófono': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/cidadao_lusofono.png',
  'Colecionador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/Colecionador.png',
  'Comunicador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/comunicador.png',
  'Corredor de Orientação': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/corredor_orientacao.png',
  'Cozinheiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/cozinheiro.jpg',
  'Cozinheiro do Mundo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/cozinheiro_mundo.png',
  'Cuidador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/cuidador.png',
  'Culturas do Mundo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/culturas_mundo.png',
  'Dança': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/danc%CC%A7a.jpg',
  'Desenhador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/desenhador.png',
  'Desportista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/desportista.png',
  'Desportos de Deslize sobre Água': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/Deslize-sobre-agua.png',
  'Despostos de Deslize sobre Rodas': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/02/Deslize-sobre-rodas.png',
  'Doméstico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/dome%CC%81stico.jpg',
  'Editor de Video': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/editor_video.png',
  'Eletricista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/eletricista.jpg',
  'Eletrónica': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/electronica-especialidade.png',
  'Energia': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/Energia.png',
  'Escalador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/escalador.png',
  'Especialista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/especialista.png',
  'Física': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/Fisica.png',
  'Fogo de Conselho': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/02/Fogo-Conselho.png',
  'Fotógrafo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/fotografo.png',
  'Fotógrafo Naturalista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/naturalista.png',
  'Geocaching': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/02/geocaching.png',
  'Geógrafo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/geografo.png',
  'Geólogo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/geologo.png',
  'Guarda-Rios': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/guarda_rios.png',
  'Guia de Região': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/guia-de-regiao.jpg',
  'Guia do Patrimonio Religioso': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Guia-Patrimonio.png',
  'Herpetólogo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/herpetologo.png',
  'Historiador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Historiador.png',
  'Informático': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/informatica.jpg',
  'Intendente': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/02/Intendente.png',
  'Intérprete': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Interprete.png',
  'Jogos de Mesa': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/jogos-de-mesa.png',
  'Jornalista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/jornalista.png',
  'Leis e Justiça': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/Leis-e-Justic%CC%A7a.png',
  'Leitor': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/leitor.png',
  'Lider de Expedição': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/lider_expedicao.png',
  'Malacolista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/malacolista.png',
  'Marinharia': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/marinharia.png',
  'Matemático': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/Matema%CC%81tico.png',
  'Mergulhador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/mergulhador.png',
  'Mérito': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/merito.png',
  'Mestre do Leme': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/mestre_motorista.png',
  'Mecânico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/metalurgico.jpg',
  'Metereologista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/meteorologista.png',
  'Modelismo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/modelismo-especialidade.png',
  'Montanhista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/montanhista.png',
  'Músico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/mu%CC%81sico.jpg',
  'Músico Liturgico': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/musico-liturgico.jpg',
  'Nadador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/nadador.png',
  'Nadador Salvador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/nadador-salvador-site.png',
  'Oceanógrafo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/oceanografo.png',
  'Ornitólogo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/ornitologo.png',
  'Pedestrianista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/pedestrianista.png',
  'Pedreiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/pedreiro.png',
  'Pescador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/pescador.png',
  'Pioneirista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/pioneirista.png',
  'Proteção Civil': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/12/Protecao-civil.png',
  'Protetor dos Animais': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Protetor-Animais.png',
  'Quimica': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/quimica-site.png',
  'Radioamador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/radioamador.png',
  'Radioescuteiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/radioescuteiro.png',
  'Realizador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/realizador-especialidade.png',
  'Reciclador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/reciclador.png',
  'Relações Publicas': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/relacoes_publicas.png',
  'Robótica': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/robotica.png',
  'Saltimbanco': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/saltimbanco.jpg',
  'Sapador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/sapador.jpg',
  'Sinaleiro': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/sinaleiro.png',
  'Sobrevivência': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2022/11/sobrevivencia.png',
  'Socorrista': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Socorrista.png',
  'Técnica Aeronáutica': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/tecnica-aeronautica.jpg',
  'Topógrafo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/topografo.png',
  'Trabalhos Manuais': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/trabalhos-manuais-e-bricolagem.jpg',
  'Tradutor': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/tradutor.png',
  'Turismo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/ada3b514-cd29-4e88-a3ce-196ab8ada43d.png',
  'Velejador': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/08/velejador.png',
  'Vigilante da Natureza': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Vigilante-Natureza.png',
  'Voluntário Internacional': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2021/07/Voluntario-Internacional.png',
  'Zoólogo': 'https://especialidades.escutismo.pt/wp-content/uploads/sites/18/2025/01/zoologo.jpg'
};

export function getEspecialidadesBadgeUrl(especialidade?: string): string | null {
  if (!especialidade) return null;
  return ESPECIALIDADES_BADGE_MAP[especialidade] || null;
}
